STREAMS_MERGER_DYNAMIC_WORKFLOW:
  extends: .deploy
  stage: deploy
  variables:
    MODULE_NAME: "streams_merger_dynamic_workflow"
    DAG: "streams_dynamic_workflow_merger_dag.py"
    JAR: "./${MODULE_NAME}/target/${SCALA}/${MODULE_NAME}.jar"
    VARS: "./deploy/vars/${MODULE_NAME}_params.json"
    HOST_AIRFLOW: ${VANILLA_AIRFLOW}
  when: manual
